name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of gemini-mcp are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      description: Which transport mode are you using?
      options:
        - stdio
        - sse
        - streamable-http
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment
      description: How are you running gemini-mcp?
      options:
        - Docker
        - Local (pip install)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Configure with ...
        2. Call tool ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages or logs.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS:
        - Python version:
        - MCP client (Claude Code / Gemini CLI / other):
        - Docker version (if applicable):
      render: markdown

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste relevant log output (set `GEMINI_MCP_LOG_LEVEL=DEBUG` for verbose logs).
      render: shell
