name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or behavior you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've thought about?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of gemini-mcp does this relate to?
      options:
        - Core tools (gemini, analyze, search)
        - Swarm system
        - Debate system
        - Plugin system
        - Configuration
        - Docker / deployment
        - Security
        - Documentation
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples.
